services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: tail -f /dev/null
    container_name: app
    environment:
      - PORT=${PORT:-3000}
    ports:
      - '9000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin4}
    depends_on:
      - db
