services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    environment:
      - PORT=${PORT:-3000}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
