services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    environment:
      - PORT=${PORT:-3000}
    ports:
      - '127.0.0.1:9000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin4}
    depends_on:
      - db
